#!/opt/.virtualenvs/magento/bin/python3.6
# coding: utf-8

import argparse
import sys
import os

from helpers import execute


parser = argparse.ArgumentParser(prog='jump')

parser.add_argument('--deploy', 
    metavar='env',
    type=str,
    nargs=1, 
    help='the environment to deploy', 
    default=argparse.SUPPRESS,
    choices=['homolog', 'production'])

parser.add_argument('--upgrade', 
    help='update jump utilitary script', 
    metavar='target',
    nargs=1,
    type=str,
    choices=['jumpa'])


execute(parser)