#!/opt/.virtualenvs/magento/bin/python3.6
# coding: utf-8

import argparse

from jump.helpers import execute, get_env


parser = argparse.ArgumentParser(prog='jump')

parser.add_argument('--deploy', 
    metavar='env',
    type=str,
    nargs=1, 
    help='the environment to deploy', 
    default=argparse.SUPPRESS,
    choices=['homolog', 'production'])

parser.add_argument('--upgrade', 
    help='upgrade composer, pip, jump script', 
    metavar='target',
    nargs=1,
    type=str,
    choices=['jump'])

execute(parser)